"""initial phase one schema"""

import sqlalchemy as sa

from alembic import op

revision = "9d958c8d8244"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total_media_entries", sa.Integer(), nullable=False),
        sa.Column("valid_images", sa.Integer(), nullable=False),
        sa.Column("uploaded_images", sa.Integer(), nullable=False),
        sa.Column("duplicate_images", sa.Integer(), nullable=False),
        sa.Column("skipped_images", sa.Integer(), nullable=False),
        sa.Column("failed_images", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_batches_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "imported_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("original_media_name", sa.String(length=1000), nullable=False),
        sa.Column("imagekit_file_id", sa.String(length=255), nullable=True),
        sa.Column("imagekit_file_path", sa.String(length=1000), nullable=True),
        sa.Column("image_url", sa.String(length=2000), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=2000), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("linked_product_id", sa.Integer(), nullable=True),
        sa.Column("duplicate_of_product_id", sa.Integer(), nullable=True),
        sa.Column("duplicate_of_imported_image_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence_number > 0", name="ck_image_sequence"),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["duplicate_of_imported_image_id"], ["imported_images.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["duplicate_of_product_id"], ["products.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["linked_product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("imported_images", schema=None) as batch_op:
        batch_op.create_index(
            "ix_imported_images_batch_status", ["batch_id", "status"], unique=False
        )
        batch_op.create_index("ix_imported_images_sha256", ["sha256"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("imagekit_file_id", sa.String(length=255), nullable=False),
        sa.Column("imagekit_file_path", sa.String(length=1000), nullable=False),
        sa.Column("image_url", sa.String(length=2000), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2000), nullable=True),
        sa.Column("image_sha256", sa.String(length=64), nullable=False),
        sa.Column("image_mime_type", sa.String(length=50), nullable=False),
        sa.Column("image_width", sa.Integer(), nullable=False),
        sa.Column("image_height", sa.Integer(), nullable=False),
        sa.Column("source_imported_image_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_product_name"),
        sa.ForeignKeyConstraint(
            ["source_imported_image_id"], ["imported_images.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_imported_image_id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index("ix_products_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_products_image_sha256", ["image_sha256"], unique=False)
        batch_op.create_index("ix_products_normalized_name", ["normalized_name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index("ix_products_normalized_name")
        batch_op.drop_index("ix_products_image_sha256")
        batch_op.drop_index("ix_products_created_at")

    op.drop_table("products")
    with op.batch_alter_table("imported_images", schema=None) as batch_op:
        batch_op.drop_index("ix_imported_images_sha256")
        batch_op.drop_index("ix_imported_images_batch_status")

    op.drop_table("imported_images")
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_batches_created_at"))

    op.drop_table("import_batches")
    # ### end Alembic commands ###
